services:
  postgres:
    image: postgres:15
    container_name: spring-demo-db
    environment:
      POSTGRES_DB: spring_demo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: spring_demo_redis
    ports:
      - "6379:6379"