ALTER TABLE products ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE tags ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE tags ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;