# Local database

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_demo
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

# Detailed logs in dev

spring.jpa.show-sql=true
logging.level.com.julian=DEBUG
logging.level.org.springframework.web=DEBUG

# Swagger active in dev

springdoc.swagger-ui.enabled=true
logging.level.org.hibernate.stat=WARN

# Redis

spring.data.redis.host=localhost
spring.data.redis.port=6379