# Database in production - use environment variables

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Minimum logs in prod

spring.jpa.show-sql=false
logging.level.com.julian=INFO
logging.level.org.springframework.web=WARN

# Swagger disabled in prod

springdoc.swagger-ui.enabled=false